# Generated by Django 3.2.7 on 2021-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='sessions_left',
            field=models.IntegerField(default=7, help_text='Amount of times this visitor pass can be used.'),
        ),
    ]
